

GET http://localhost:4000/list


###

GET http://localhost:4000/list/600f255ad16e8f2aa875d665

###

POST http://localhost:4000/list
Content-Type: application/json

{
    "name": "kolejna",
    "tasks": ["kolje ne"]
}

###
PATCH http://localhost:4000/list/601705cf66e8c635684b95b9
Content-Type: application/json

{
    "name": "Druga",
    "tasks": [{"name": "pierwysz", "isDone": true, "_id": "1"},{"name": "drugi", "isDone": false, "_id": "2"},{"name": "trzeci", "isDone": false, "_id": "3"},{"name": "trzeci", "isDone": true, "_id": "5"},{"name": "trzeci", "isDone": false, "_id": "6"}]
}
